enum TechnologyTags {
  DeepLearning = 'Deep Learning',
  ArtificialIntelligence = 'Artificial Intelligence',
  SQL = 'SQL',
  NoSQL = 'NoSQL',
  Containerization = 'Containerization',
  DevOps = 'DevOps',
  DataVisualization = 'Data Visualization',
  RealTime = 'Real Time',
  MachineLearning = 'Machine Learning',
  ReinforcementLearning = 'Reinforcement Learning',
  TimeSeries = 'Time Series',
  Graphs = 'Graphs',
  YAGNI = 'YAGNI',
  DRY = 'DRY',
  DDD = 'DDD',
  SOLID = 'SOLID',
  FunctionalProgramming = 'Functional Programming',
  OOP = 'OOP',
  TDD = 'TDD',
  BDD = 'BDD',
  TDD_BDD = 'TDD/BDD',
  Agile = 'Agile',
  Scrum = 'Scrum',
  Kanban = 'Kanban',
  Waterfall = 'Waterfall',
  XP = 'XP',
  Lean = 'Lean',
  KISS = 'KISS',
  Microservices = 'Microservices',
  Kubernetes = 'Kubernetes',
  MVVM = 'MVVM',
  Hexagonal = 'Hexagonal',
  SSG = 'SSG',
  SSR = 'SSR',
  SPA = 'SPA',
  ISR = 'ISR',
  REST = 'REST',
  SOAP = 'SOAP',
  Serverless = 'Serverless',
  Multithreaded = 'Multithreaded'
}

enum TechnologyTypes {
  Language = 'Language',
  Framework = 'Framework',
  Library = 'Library',
  DataLibrary = 'Data science library',
  Tool = 'Tool',
  Database = 'Database',
  Automation = 'Automation',
  Ecosystem = 'Ecosystem',
  Cloud = 'Cloud',
  Other = 'Other'
}

enum Categories {
  Frontend = 'Frontend',
  Fullstack = 'Fullstack',
  Backend = 'Backend',
  DevOps = 'DevOps',
  Cloud = 'Cloud',
  DataEngineering = 'Data engineering',
  MachineLearning = 'Machine learning',
  DataScience = 'Data science',
  DataAnalyst = 'Data analyst',
  Algorithmic = 'Algorithmic',
  Mobile = 'Mobile',
  UXUI = 'UXUI',
  Gamedev = 'Gamedev',
  Salesforce = 'Salesforce',
  Embedded = 'Embedded',
  BigData = 'Big data'
}

export { TechnologyTags, TechnologyTypes, Categories }
